using System.Linq;
using Fargowiltas.Items.CaughtNPCs;
using Fargowiltas.NPCs;
using Fargowiltas.Utilities;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace Fargowiltas.Common.Systems.Recipes;

public class NPCRecipeSystem : ModSystem
{
	internal static int AnyCaughtNPC;

	public override void AddRecipeGroups()
	{
		RecipeGroup group = new RecipeGroup(() => RecipeHelper.GenerateAnyItemRecipeGroupText("CaughtNPC"), CaughtNPCItem.CaughtTownies.Values.ToArray());
		AnyCaughtNPC = RecipeGroup.RegisterGroup("Fargowiltas:AnyCaughtNPC", group);
	}

	public override void AddRecipes()
	{
		AddNPCRecipes();
		AddSkeletonMerchantNPCRecipes();
		AddTravellingMerchantNPCRecipes();
	}

	private static void AddNPCRecipes()
	{
		Recipe recipe = Recipe.Create(763, 25);
		recipe.AddRecipeGroup(AnyCaughtNPC);
		recipe.AddTile(218);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(1085, 20);
		recipe.AddRecipeGroup(AnyCaughtNPC);
		recipe.AddTile(228);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(4663, 2);
		recipe.AddRecipeGroup(AnyCaughtNPC);
		recipe.AddTile(228);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(1376);
		recipe.AddRecipeGroup(AnyCaughtNPC);
		recipe.AddTile(300);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(1377);
		recipe.AddRecipeGroup(AnyCaughtNPC);
		recipe.AddTile(300);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(1417);
		recipe.AddRecipeGroup(AnyCaughtNPC);
		recipe.AddTile(300);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(1081, 20);
		recipe.AddIngredient(CaughtNPCItem.CaughtTownies[160]);
		recipe.AddTile(228);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(CaughtNPCItem.CaughtTownies[ModContent.NPCType<Squirrel>()]);
		recipe.AddRecipeGroup(RecipeGroups.AnySquirrel);
		recipe.AddIngredient(239);
		recipe.AddTile(26);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(CaughtNPCItem.CaughtTownies[368]);
		recipe.AddIngredient(null, "Merchant");
		recipe.AddIngredient(73, 50);
		recipe.AddIngredient(1015);
		recipe.AddTile(228);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(933);
		recipe.AddIngredient(null, "Dryad");
		recipe.AddTile(304);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2673);
		recipe.AddIngredient(null, "Truffle");
		recipe.AddIngredient(3191);
		recipe.AddTile(247);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3349);
		recipe.AddIngredient(null, "DyeTrader");
		recipe.AddIngredient(24);
		recipe.AddTile(26);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3821);
		recipe.AddIngredient(null, "Tavernkeep");
		recipe.AddIngredient(353, 5);
		recipe.AddTile(26);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3352);
		recipe.AddIngredient(null, "Stylist");
		recipe.AddIngredient(24);
		recipe.AddTile(26);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3350);
		recipe.AddIngredient(null, "Painter");
		recipe.AddIngredient(39);
		recipe.AddTile(26);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3351);
		recipe.AddIngredient(null, "TaxCollector");
		recipe.AddIngredient(24);
		recipe.AddTile(26);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(5065);
		recipe.AddIngredient(null, "Princess");
		recipe.AddIngredient(1508);
		recipe.AddTile(26);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(4818);
		recipe.AddIngredient(null, "Mechanic");
		recipe.AddIngredient(284);
		recipe.AddTile(26);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3120);
		recipe.AddIngredient(null, "Angler");
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3037);
		recipe.AddIngredient(null, "Angler");
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3096);
		recipe.AddIngredient(null, "Angler");
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3750);
		recipe.AddIngredient(4326);
		recipe.AddIngredient(null, "PartyGirl");
		recipe.AddTile(17);
		recipe.DisableDecraft();
		recipe.Register();
	}

	private static void AddSkeletonMerchantNPCRecipes()
	{
		Recipe recipe = Recipe.Create(CaughtNPCItem.CaughtTownies[368]);
		recipe.AddIngredient(null, "SkeletonMerchant");
		recipe.AddTile(218);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(154, 25);
		recipe.AddIngredient(null, "SkeletonMerchant");
		recipe.AddTile(300);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3310);
		recipe.AddIngredient(null, "SkeletonMerchant");
		recipe.AddIngredient(73, 10);
		recipe.AddIngredient(1015);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3313);
		recipe.AddIngredient(null, "SkeletonMerchant");
		recipe.AddIngredient(73, 10);
		recipe.AddIngredient(1007);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3312);
		recipe.AddIngredient(null, "SkeletonMerchant");
		recipe.AddIngredient(73, 10);
		recipe.AddIngredient(1016);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3311);
		recipe.AddIngredient(null, "SkeletonMerchant");
		recipe.AddIngredient(73, 10);
		recipe.AddIngredient(1011);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3316);
		recipe.AddIngredient(null, "SkeletonMerchant");
		recipe.AddIngredient(73, 40);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.Hardmode);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3315);
		recipe.AddIngredient(null, "SkeletonMerchant");
		recipe.AddIngredient(73, 40);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.Hardmode);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3043);
		recipe.AddIngredient(null, "SkeletonMerchant", 2);
		recipe.AddIngredient(73, 20);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
	}

	private static void AddTravellingMerchantNPCRecipes()
	{
		Recipe recipe = Recipe.Create(CaughtNPCItem.CaughtTownies[453]);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddIngredient(154, 5);
		recipe.AddTile(300);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2260, 500);
		recipe.AddIngredient(9, 500);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddTile(96);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2274, 200);
		recipe.AddIngredient(8, 200);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3099);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddIngredient(73, 10);
		recipe.AddRecipeGroup(RecipeGroupID.IronBar, 5);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3118);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddIngredient(73, 10);
		recipe.AddRecipeGroup(RecipeGroupID.IronBar, 5);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3119);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddIngredient(73, 10);
		recipe.AddRecipeGroup(RecipeGroupID.IronBar, 5);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2273);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddIngredient(73, 20);
		recipe.AddRecipeGroup(RecipeGroupID.IronBar, 5);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.NotRemixWorld);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3624);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddIngredient(73, 20);
		recipe.AddIngredient(849, 10);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2217);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddIngredient(73, 20);
		recipe.AddIngredient(2325);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2216);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddIngredient(73, 20);
		recipe.AddIngredient(2325);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2215);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddIngredient(73, 20);
		recipe.AddIngredient(2325);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2214);
		recipe.AddIngredient(null, "TravellingMerchant");
		recipe.AddIngredient(73, 20);
		recipe.AddIngredient(2325);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3262);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 10);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.DownedEyeOfCthulhu);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3284);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 50);
		recipe.AddIngredient(3262);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.DownedMechBossAny);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(4347);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 34);
		recipe.AddIngredient(127);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(4348);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(74);
		recipe.AddIngredient(4347);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.Hardmode);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(4365);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(74, 2);
		recipe.AddIngredient(109);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2277);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 4);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2279);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 7);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2275);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 6);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2269);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 20);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.DownedEowOrBoc);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(4550);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(74, 2);
		recipe.AddIngredient(4564, 25);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(4605);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(74, 2);
		recipe.AddIngredient(1999);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(4604);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(74, 2);
		recipe.AddIngredient(276, 50);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(4603);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(74, 2);
		recipe.AddIngredient(320, 10);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3628);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(74, 10);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2296);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 70);
		recipe.AddRecipeGroup(RecipeGroups.AnyDuck);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.DownedSkeletron);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2276);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(74, 4);
		recipe.AddIngredient(182);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2272);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 3);
		recipe.AddIngredient(206);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2223);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 90);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.DownedMechBossAll);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3314);
		recipe.AddIngredient(null, "TravellingMerchant", 2);
		recipe.AddIngredient(73, 10);
		recipe.AddIngredient(1009);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(4760);
		recipe.AddIngredient(null, "TravellingMerchant", 4);
		recipe.AddIngredient(73, 70);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.Hardmode);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(2270);
		recipe.AddIngredient(null, "TravellingMerchant", 4);
		recipe.AddIngredient(73, 70);
		recipe.AddTile(114);
		recipe.AddCondition(Condition.Hardmode);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(3309);
		recipe.AddIngredient(null, "TravellingMerchant", 4);
		recipe.AddIngredient(73, 10);
		recipe.AddIngredient(1050);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
		recipe = Recipe.Create(1987);
		recipe.AddIngredient(null, "TravellingMerchant", 5);
		recipe.AddIngredient(73, 80);
		recipe.AddIngredient(19, 5);
		recipe.AddTile(114);
		recipe.DisableDecraft();
		recipe.Register();
	}
}
